FROM node:26.2.0-trixie-slim

# Install `git` for VCS
# Install `vim` to be able to edit `git commit` messages properly in terminal
RUN apt update  -y &&           \
    apt upgrade -y &&           \
    apt install -y              \
        --no-install-recommends \
        build-essential         \
        ca-certificates         \
        git                     \
        ssh                     \
        vim                     \
    &&                          \
    apt autoremove &&           \
    apt clean

# Switch to the lesser privileged user
USER node